### ISSUE TITLE
Setting a custom gitPath results in a fatal error

### ISSUE THREAD

**Issue by ReLater** [DigiLive/gitChangelog#12]
**Describe**
- In a local Git repository I have a subfolder that contains my PHP scripts and also the composer /vendor/ folder.
- Therefore the default `gitPath` (`./.git`) is wrong and I get error `fatal: not a git repository: './.git'`.
- I tried your little example code and tried to adapt the `gitPath` like this:

```
...
...

// Instantiate the library's renderer.
$changelog = new MarkDown();

// My trial to change gitPath.
$changelog->gitPath = '../.git';

...
...
```

Because I still get an error pointing to the default (`./.git`) it looks like that my approach is completely wrong.

`fatal: not a git repository: './.git' ... GitChangelog.php:202`

When I try (just for tests) to change at https://github.com/DigiLive/gitChangelog/blob/v1.0.1/src/GitChangelog.php#L83

`public $gitPath;`

to

`public $gitPath = '../.git';`

I get error
`fatal: not a git repository: '../.git.git' ... GitChangelog.php:288`

When I change it to `public $gitPath = '../';` I get error
`fatal: not a git repository: '../' ... GitChangelog.php:202`

Question: Is there an option or setter in the PHP package to customise the gitPath without harsh overrides? Until now I couldn't find one in code.

Thank you!

**Comment by DigiLive** [comment]
There was a bug indeed, which should be resolved at the commit mentioned above.
Please try this commit and feedback the results.

You can set a custom repository path by setting the gitPath property.
```php
// Instantiate the library's renderer.
$changelog = new MarkDown();

// My trial to change gitPath.
$changelog->gitPath = '../';
```

**Comment by ReLater** [comment]
- Followed your commit and changed the code in GitChangelog.php.
- Used `$changelog->gitPath = '../';` in my code.

I still get the error pointing to the default path.

```
fatal: not a git repository: './.git'

PHP Fatal error:  Uncaught RuntimeException: An error occurred while fetching the tags from the repository! in /mnt/z/git-kram/hugo_docsghsvs/buildBefore/vendor/digilive/git-changelog/src/GitChangelog.php:202
Stack trace:
#0 /mnt/z/git-kram/hugo_docsghsvs/buildBefore/vendor/digilive/git-changelog/src/GitChangelog.php(168): DigiLive\GitChangelog\GitChangelog->fetchTags()
#1 /mnt/z/git-kram/hugo_docsghsvs/buildBefore/git-changelog.php(13): DigiLive\GitChangelog\GitChangelog->__construct()
#2 {main}
  thrown in /mnt/z/git-kram/hugo_docsghsvs/buildBefore/vendor/digilive/git-changelog/src/GitChangelog.php on line 202
```

When I add a debug line in GitChangelog.php line 194:
`echo ' DEBUG:  ' . is_null($this->gitPath) . PHP_EOL;exit;`

it says that `$this->gitPath` is NULL and not populated with string `'../'`.

**Comment by DigiLive** [comment]
Yeah... I have to change some stuff about using custom repository location.

Try setting the custom location and force re-fetching the git tags:
```php
// Instantiate the library's renderer.
$changelog = new MarkDown();

// My trial to change gitPath.
$changelog->gitPath = '../';
$changelog->fetchTags(true);
```

**Comment by DigiLive** [comment]
Pull the latest commit of the main branch and try
```php
// Instantiate the library's renderer.
$changelog = new MarkDown('../');
```

**Comment by ReLater** [comment]
Thanks a lot for spending time with this issue. It finds the path to `/.git/` now correctly.

**Comment by DigiLive** [comment]
You're very welcome.
I will release a new version very soon and update the wiki according to the changes.

Thank you for reporting, please add another issue if you have any problems or ideas.
